# Generated by Django 4.2 on 2023-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('latitude', models.FloatField(max_length=10)),
                ('longitude', models.FloatField(max_length=10)),
                ('ignition_status', models.BooleanField()),
                ('movement_status', models.BooleanField()),
                ('power_voltage', models.FloatField(max_length=10)),
                ('battery_voltage', models.FloatField(max_length=10)),
                ('can_engine_coolant_temp', models.IntegerField(max_length=8)),
                ('can_engine_intake_air_temp', models.IntegerField(max_length=8)),
                ('can_engine_rpm', models.IntegerField(max_length=8)),
                ('can_engine_load_level', models.IntegerField(max_length=8)),
                ('can_vehicle_speed', models.IntegerField(max_length=8)),
                ('ble_temperature_1', models.FloatField(max_length=8)),
                ('ble_temperature_2', models.FloatField(max_length=8)),
                ('ble_humidity_1', models.FloatField(max_length=8)),
                ('ble_humidity_2', models.FloatField(max_length=8)),
            ],
        ),
    ]
