# Generated by Django 4.2 on 2023-06-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_trackerdata_battery_voltage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMetadata',
            fields=[
                ('trip_index', models.IntegerField(primary_key=True, serialize=False)),
                ('start_timestamp', models.BigIntegerField()),
                ('end_timestamp', models.BigIntegerField()),
            ],
            options={
                'ordering': ['trip_index'],
            },
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.tripmetadata'),
        ),
    ]
