# Generated by Django 4.2 on 2023-04-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('zalgiris_score', models.IntegerField(blank=True)),
                ('barcelona_score', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Totalizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('zalgiris_guess', models.IntegerField()),
                ('barcelona_guess', models.IntegerField()),
                ('guess_accuracy', models.FloatField(blank=True)),
                ('game_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zalgiris.gamescore')),
            ],
        ),
    ]
