# Generated by Django 4.2 on 2023-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalgiris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalizator',
            name='guess_accuracy',
            field=models.FloatField(null=True),
        ),
    ]
